//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingfisher.Controls.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kingfisher.Controls.Config.ConfigResources", typeof(ConfigResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AgeOfBuilds_After {
            get {
                return ResourceManager.GetString("AgeOfBuilds_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get builds from the last.
        /// </summary>
        internal static string AgeOfBuilds_Before {
            get {
                return ResourceManager.GetString("AgeOfBuilds_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get builds of the last {0}.
        /// </summary>
        internal static string AgeOfBuildsInSeconds {
            get {
                return ResourceManager.GetString("AgeOfBuildsInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string Autostart_Header {
            get {
                return ResourceManager.GetString("Autostart_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hide when starting automatically.
        /// </summary>
        internal static string Autostart_hidden {
            get {
                return ResourceManager.GetString("Autostart_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Automatically start application when windows starts.
        /// </summary>
        internal static string Autostart_when_Windows_starts {
            get {
                return ResourceManager.GetString("Autostart_when_Windows_starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevOps Server Settings.
        /// </summary>
        internal static string DevOps_Server_Settings {
            get {
                return ResourceManager.GetString("DevOps_Server_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevOps _Server Url (with collection):.
        /// </summary>
        internal static string DevOps_Server_Url {
            get {
                return ResourceManager.GetString("DevOps_Server_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RefreshBuilds_After {
            get {
                return ResourceManager.GetString("RefreshBuilds_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh builds every.
        /// </summary>
        internal static string RefreshBuilds_Before {
            get {
                return ResourceManager.GetString("RefreshBuilds_Before", resourceCulture);
            }
        }
    }
}
